name: "Bug report"
description: Experiencing issues with 10to7? Let us know here.
labels: [Bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        > [!WARNING]
        > Please fill out this document according to the format, otherwise I will simply close the issue.

  - type: checkboxes
    attributes:
      label: Before reporting your issue
      description: Please ensure you meet the following criteria before reporting issues
      options:
        - label: My version of Windows is up to date (Atleast up to April 2024 as per update warning)
        - label: I'm running the latest version or the one prior of the Windows 10to7 Transformation Pack (I checked the changelog on the downloads page before opening the issue).


  - type: input
    attributes:
      label: What version of Windows 10 are you using the transformation pack on?
      description: "Example: Windows 10 LTSC 2021 21H2 19044.5011"
    validations:
      required: true

  - type: input
    attributes:
      label: What version of the Transformation Pack are you having issues with?
      description: "If you have issues upgrading a transformation pack version, please specify. For example: 21H2to7 3.5.3 to 3.5.4."
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Summarise the issue
      description: Provide a clear, concise description of the bug or inaccuracy.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help illustrate the issue
      placeholder: Drop or paste images or videos to upload.

  - type: textarea
    attributes:
      label: How do you reproduce the bug/inaccuracy?
      description: List the steps to reproduce the issue
      placeholder: "1.\n2.\n3.\n4. ..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, such as frequency of the issue, etc.
