name: Feature request
description: Want to suggest a feature for 10to7? Share your ideas here!
labels: [enhancement]
assignees: []

body:
  - type: checkboxes
    attributes:
      label: Before sending your suggestion
      description: Before submitting your suggestions, please make sure you meet the following criteria
      options:
        - label: My version of Windows is up to date (Atleast up to April 2024 as per update warning)
        - label: I'm running the latest version of the Windows 10to7 Transformation Pack.

  - type: input
    attributes:
      label: What version of Windows 10 are you using the transformation pack on?
      description: "Example: Windows 10 LTSC 2021 21H2 19044.5011"
    validations:
      required: true

  - type: textarea
    attributes:
      label: What would you like to suggest for 21H2to7?
      description: Provide a clear, concise description of the suggestion.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: Add other context about the suggestion here, such as reference images, etc.
