name: Issue Manager

on:
  issues:
    types:
      - labeled

jobs:
  on_duplicate:
    if: github.event.label.name == 'duplicate'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@5f728c3dae25f329afbe34ee4d08eef25569d79f
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This issue is a duplicate!

            Please make sure to check for existing issues in this repository before submitting an issue.  
            If you believe this is a mistake, feel free to reply.
      - name: Close issue
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: "closed",
              state_reason: "not_planned"
            });